/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WizardKittenzRouteImport } from './routes/wizard-kittenz'
import { Route as BourbonDojoIndexRouteImport } from './routes/bourbon-dojo/index'
import { Route as BourbonDojoPrivacyRouteImport } from './routes/bourbon-dojo/privacy'
import { Route as WizardKittenzPrivacyRouteImport } from './routes/wizard-kittenz.privacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardKittenzRoute = WizardKittenzRouteImport.update({
  id: '/wizard-kittenz',
  path: '/wizard-kittenz',
  getParentRoute: () => rootRouteImport,
} as any)
const BourbonDojoIndexRoute = BourbonDojoIndexRouteImport.update({
  id: '/bourbon-dojo/',
  path: '/bourbon-dojo/',
  getParentRoute: () => rootRouteImport,
} as any)
const BourbonDojoPrivacyRoute = BourbonDojoPrivacyRouteImport.update({
  id: '/bourbon-dojo/privacy',
  path: '/bourbon-dojo/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardKittenzPrivacyRoute = WizardKittenzPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => WizardKittenzRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wizard-kittenz': typeof WizardKittenzRouteWithChildren
  '/bourbon-dojo/privacy': typeof BourbonDojoPrivacyRoute
  '/wizard-kittenz/privacy': typeof WizardKittenzPrivacyRoute
  '/bourbon-dojo/': typeof BourbonDojoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wizard-kittenz': typeof WizardKittenzRouteWithChildren
  '/bourbon-dojo/privacy': typeof BourbonDojoPrivacyRoute
  '/wizard-kittenz/privacy': typeof WizardKittenzPrivacyRoute
  '/bourbon-dojo': typeof BourbonDojoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wizard-kittenz': typeof WizardKittenzRouteWithChildren
  '/bourbon-dojo/privacy': typeof BourbonDojoPrivacyRoute
  '/wizard-kittenz/privacy': typeof WizardKittenzPrivacyRoute
  '/bourbon-dojo/': typeof BourbonDojoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/wizard-kittenz'
    | '/bourbon-dojo/privacy'
    | '/wizard-kittenz/privacy'
    | '/bourbon-dojo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/wizard-kittenz'
    | '/bourbon-dojo/privacy'
    | '/wizard-kittenz/privacy'
    | '/bourbon-dojo'
  id:
    | '__root__'
    | '/'
    | '/wizard-kittenz'
    | '/bourbon-dojo/privacy'
    | '/wizard-kittenz/privacy'
    | '/bourbon-dojo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WizardKittenzRoute: typeof WizardKittenzRouteWithChildren
  BourbonDojoPrivacyRoute: typeof BourbonDojoPrivacyRoute
  BourbonDojoIndexRoute: typeof BourbonDojoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard-kittenz': {
      id: '/wizard-kittenz'
      path: '/wizard-kittenz'
      fullPath: '/wizard-kittenz'
      preLoaderRoute: typeof WizardKittenzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bourbon-dojo/': {
      id: '/bourbon-dojo/'
      path: '/bourbon-dojo'
      fullPath: '/bourbon-dojo/'
      preLoaderRoute: typeof BourbonDojoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bourbon-dojo/privacy': {
      id: '/bourbon-dojo/privacy'
      path: '/bourbon-dojo/privacy'
      fullPath: '/bourbon-dojo/privacy'
      preLoaderRoute: typeof BourbonDojoPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard-kittenz/privacy': {
      id: '/wizard-kittenz/privacy'
      path: '/privacy'
      fullPath: '/wizard-kittenz/privacy'
      preLoaderRoute: typeof WizardKittenzPrivacyRouteImport
      parentRoute: typeof WizardKittenzRoute
    }
  }
}

interface WizardKittenzRouteChildren {
  WizardKittenzPrivacyRoute: typeof WizardKittenzPrivacyRoute
}

const WizardKittenzRouteChildren: WizardKittenzRouteChildren = {
  WizardKittenzPrivacyRoute: WizardKittenzPrivacyRoute,
}

const WizardKittenzRouteWithChildren = WizardKittenzRoute._addFileChildren(
  WizardKittenzRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WizardKittenzRoute: WizardKittenzRouteWithChildren,
  BourbonDojoPrivacyRoute: BourbonDojoPrivacyRoute,
  BourbonDojoIndexRoute: BourbonDojoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
