/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BourbonDojoIndexRouteImport } from './routes/bourbon-dojo/index'
import { Route as BourbonDojoPrivacyRouteImport } from './routes/bourbon-dojo/privacy'
import { Route as WizardKittenzIndexRouteImport } from './routes/wizard-kittenz/index'
import { Route as WizardKittenzPrivacyRouteImport } from './routes/wizard-kittenz/privacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BourbonDojoIndexRoute = BourbonDojoIndexRouteImport.update({
  id: '/bourbon-dojo/',
  path: '/bourbon-dojo/',
  getParentRoute: () => rootRouteImport,
} as any)
const BourbonDojoPrivacyRoute = BourbonDojoPrivacyRouteImport.update({
  id: '/bourbon-dojo/privacy',
  path: '/bourbon-dojo/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardKittenzIndexRoute = WizardKittenzIndexRouteImport.update({
  id: '/wizard-kittenz/',
  path: '/wizard-kittenz/',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardKittenzPrivacyRoute = WizardKittenzPrivacyRouteImport.update({
  id: '/wizard-kittenz/privacy',
  path: '/wizard-kittenz/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bourbon-dojo/privacy': typeof BourbonDojoPrivacyRoute
  '/wizard-kittenz/privacy': typeof WizardKittenzPrivacyRoute
  '/bourbon-dojo/': typeof BourbonDojoIndexRoute
  '/wizard-kittenz/': typeof WizardKittenzIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bourbon-dojo/privacy': typeof BourbonDojoPrivacyRoute
  '/wizard-kittenz/privacy': typeof WizardKittenzPrivacyRoute
  '/bourbon-dojo': typeof BourbonDojoIndexRoute
  '/wizard-kittenz': typeof WizardKittenzIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bourbon-dojo/privacy': typeof BourbonDojoPrivacyRoute
  '/wizard-kittenz/privacy': typeof WizardKittenzPrivacyRoute
  '/bourbon-dojo/': typeof BourbonDojoIndexRoute
  '/wizard-kittenz/': typeof WizardKittenzIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bourbon-dojo/privacy'
    | '/wizard-kittenz/privacy'
    | '/bourbon-dojo/'
    | '/wizard-kittenz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bourbon-dojo/privacy'
    | '/wizard-kittenz/privacy'
    | '/bourbon-dojo'
    | '/wizard-kittenz'
  id:
    | '__root__'
    | '/'
    | '/bourbon-dojo/privacy'
    | '/wizard-kittenz/privacy'
    | '/bourbon-dojo/'
    | '/wizard-kittenz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BourbonDojoPrivacyRoute: typeof BourbonDojoPrivacyRoute
  WizardKittenzPrivacyRoute: typeof WizardKittenzPrivacyRoute
  BourbonDojoIndexRoute: typeof BourbonDojoIndexRoute
  WizardKittenzIndexRoute: typeof WizardKittenzIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bourbon-dojo/': {
      id: '/bourbon-dojo/'
      path: '/bourbon-dojo'
      fullPath: '/bourbon-dojo/'
      preLoaderRoute: typeof BourbonDojoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bourbon-dojo/privacy': {
      id: '/bourbon-dojo/privacy'
      path: '/bourbon-dojo/privacy'
      fullPath: '/bourbon-dojo/privacy'
      preLoaderRoute: typeof BourbonDojoPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard-kittenz/': {
      id: '/wizard-kittenz/'
      path: '/wizard-kittenz'
      fullPath: '/wizard-kittenz/'
      preLoaderRoute: typeof WizardKittenzIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard-kittenz/privacy': {
      id: '/wizard-kittenz/privacy'
      path: '/wizard-kittenz/privacy'
      fullPath: '/wizard-kittenz/privacy'
      preLoaderRoute: typeof WizardKittenzPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BourbonDojoPrivacyRoute: BourbonDojoPrivacyRoute,
  WizardKittenzPrivacyRoute: WizardKittenzPrivacyRoute,
  BourbonDojoIndexRoute: BourbonDojoIndexRoute,
  WizardKittenzIndexRoute: WizardKittenzIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
